import * as path from 'path';

const EXT_MAP: Record<string, string> = {
  '.ts': 'typescript',
  '.tsx': 'typescriptreact',
  '.js': 'javascript',
  '.jsx': 'javascriptreact',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.py': 'python',
  '.go': 'go',
  '.rs': 'rust',
  '.java': 'java',
  '.cs': 'csharp',
  '.rb': 'ruby',
  '.php': 'php',
  '.swift': 'swift',
  '.kt': 'kotlin',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.hxx': 'cpp',
  '.m': 'objectivec',
  '.mm': 'objectivec',
  '.asm': 'assembly',
  '.s': 'assembly',
  '.S': 'assembly',
  '.f': 'fortran',
  '.f90': 'fortran',
  '.f95': 'fortran',
  '.f03': 'fortran',
  '.f08': 'fortran',
  '.cob': 'cobol',
  '.cbl': 'cobol',
  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.lua': 'lua',
  '.zig': 'zig',
  '.nim': 'nim',
  '.r': 'r',
  '.R': 'r',
  '.dart': 'dart',
  '.jl': 'julia',
  '.pl': 'perl',
  '.pm': 'perl',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.clj': 'clojure',
  '.cljs': 'clojure',
  '.cljc': 'clojure',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.scala': 'scala',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  '.html': 'html',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.md': 'markdown',
  '.json': 'json',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.sh': 'shell',
  '.bash': 'shell',
  '.sql': 'sql',
};

export const LANG_ALIASES: Record<string, string[]> = {
  ts: ['typescript', 'typescriptreact'],
  tsx: ['typescriptreact'],
  js: ['javascript', 'javascriptreact'],
  jsx: ['javascriptreact'],
  py: ['python'],
  rs: ['rust'],
  go: ['go'],
  java: ['java'],
  cs: ['csharp'],
  cpp: ['cpp'],
  cc: ['cpp'],
  cxx: ['cpp'],
  c: ['c'],
  h: ['c', 'cpp'],
  m: ['objectivec'],
  objc: ['objectivec'],
  asm: ['assembly'],
  f: ['fortran'],
  f90: ['fortran'],
  cob: ['cobol'],
  hs: ['haskell'],
  lua: ['lua'],
  zig: ['zig'],
  nim: ['nim'],
  r: ['r'],
  dart: ['dart'],
  jl: ['julia'],
  pl: ['perl'],
  ex: ['elixir'],
  clj: ['clojure'],
  erl: ['erlang'],
  scala: ['scala'],
  kt: ['kotlin'],
  php: ['php'],
  swift: ['swift'],
};

export function resolveLangAlias(input: string): string[] {
  const lower = input.toLowerCase();
  if (LANG_ALIASES[lower]) return LANG_ALIASES[lower];
  return [lower];
}

export function detectLanguage(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  return EXT_MAP[ext] ?? 'plaintext';
}
